//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace United_Blocks.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class United_BDEntities : DbContext
    {
        public United_BDEntities()
            : base("name=United_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Feedback> tb_Feedback { get; set; }
        public virtual DbSet<tb_Score> tb_Score { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
        public virtual DbSet<tb_Versao> tb_Versao { get; set; }
    }
}
