//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace United_Blocks.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Feedback
    {
        public int FDB_ID { get; set; }
        public string FDB_Nickname { get; set; }
        public string FDB_feedback { get; set; }
        public System.DateTime FDB_DateFeedback { get; set; }
    }
}
