//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace United_Blocks.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Score
    {
        public int SCR_ID { get; set; }
        public string SCR_Nickname { get; set; }
        public int SCR_Score { get; set; }
        public System.DateTime SCR_DateGame { get; set; }
        public string SCR_Level { get; set; }
    }
}
