//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace United_Blocks.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario
    {
        public int USR_ID { get; set; }
        public string USR_Nick { get; set; }
        public string USR_Senha { get; set; }
        public System.DateTime USR_DataCadastro { get; set; }
        public string USR_Email { get; set; }
    }
}
