//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace United_Blocks.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Versao
    {
        public string VRS_Versao { get; set; }
        public string VRS_LinkDownload { get; set; }
    }
}
